update to use openhrp3/hrpsys with trunk

diff --git a/openhrp3/Makefile.openhrp3 b/openhrp3/Makefile.openhrp3
--- a/openhrp3/Makefile.openhrp3
+++ b/openhrp3/Makefile.openhrp3
@@ -1,30 +1,13 @@
 INSTALL_DIR = $(CURDIR)
-FILENAME    = OpenHRP-3.1.4.zip
-TARBALL     = build/$(FILENAME)
-SOURCE_DIR  = build/OpenHRP-3.1.4
-#TARBALL_PATCH =
-UNPACK_CMD  = unzip
-MD5SUM_FILE = $(FILENAME).md5sum
-WGET_COMMAND = --post-data "fname=OpenHRP-3.1.4.zip" --no-check-certificate https://openrtp.jp/openhrp3/script-jp/download_file.php -O $(TARBALL)
-include $(shell rospack find mk)/download_unpack_build.mk
+SVN_DIR     = build/OpenHRR-3
+SVN_URL     = https://openrtp.jp/svn/hrg/openhrp/3.1/trunk
+#SVN_REVISION = r@REVISION@
+#SVN_PATCH = 
 
-$(SOURCE_DIR)/unpacked:
-	-mkdir -p build
-	 if [ "`md5sum $(TARBALL) | cut -f1 -d\ `" != "`cat $(FILENAME).md5sum | cut -f1 -d\ `" ]; then \
-	    wget $(WGET_COMMAND) || wget $(WGET_COMMAND) || wget $(WGET_COMMAND); \
-	fi
-	if [ "`md5sum $(TARBALL) | cut -f1 -d\ `" != "`cat $(FILENAME).md5sum | cut -f1 -d\ `" ]; then echo "ERROR: md5sum mismatch (`md5sum $(TARBALL) | cut -f1 -d\ ` != `cat $(FILENAME).md5sum | cut -f1 -d\ ` ), Aborting.." ; exit 1; fi
-	touch -c $(TARBALL)
-	rm -rf $(SOURCE_DIR) $(INITIAL_DIR)
-	cd build; $(UNPACK_CMD) ../$(TARBALL)
-ifneq ($(strip $(TARBALL_PATCH)),)
-	$(foreach patch,$(TARBALL_PATCH), patch -d $(SOURCE_DIR) -p0 < $(patch);)
-endif
-	touch $(SOURCE_DIR)/unpacked
+include $(shell rospack find mk)/svn_checkout.mk
 
-
-installed.openhrp3: $(SOURCE_DIR)/unpacked
-	cd $(SOURCE_DIR) && PATH=`rospack find openrtm`/bin:$(PATH) cmake . -DCMAKE_INSTALL_PREFIX=$(INSTALL_DIR) -DENABLE_INSTALL_RPATH=ON -DENABLE_INSTALL_RPATH_TO_SELF=ON && make && make install
+installed.openhrp3: $(SVN_DIR) patched
+	cd $(SVN_DIR) && PATH=`rospack find openrtm`/bin:$(PATH) cmake . -DCMAKE_INSTALL_PREFIX=$(INSTALL_DIR) -DENABLE_INSTALL_RPATH=ON -DENABLE_INSTALL_RPATH_TO_SELF=ON && make && make install
 	#
 	# copy idl
 	mkdir -p $(CURDIR)/idl && cp -p $(CURDIR)/share/OpenHRP-3.1/idl/OpenHRP/* ./idl/
@@ -34,7 +17,7 @@ installed.openhrp3: $(SOURCE_DIR)/unpacked
 
 clean.openhrp3:
 	-rm -fr installed patched include bin lib idl idl_gen share src_gen workspace build/CMakeCache.txt
-	rm -fr installed.openhrp3
+	-rm -fr installed.openhrp3
 
 java3d: lib/ext/j3dcore.jar
 ifeq ($(shell uname -m),x86_64)
@@ -74,10 +57,10 @@ build/rtmtools_eclipse.zip: build/rtmtools100release_en.zip eclipse/rtmtools
 	cd ${CURDIR}/eclipse/rtmtools; zip -urq ${CURDIR}/build/rtmtools_eclipse.zip * -x '*/.svn/*'
 
 build/grxui_eclipse.zip: build/rtmtools100release_en.zip eclipse/grxui
-	cp `rospack find openhrp3`/grxui_build_`uname -m`.xml $(SOURCE_DIR)/GrxUIonEclipse-project-0.9.8/grxui_build.xml
-	cp `rospack find openhrp3`/javaCompiler.grxui_`uname -m`.jar.args $(SOURCE_DIR)/GrxUIonEclipse-project-0.9.8/javaCompiler.grxui.jar.args
-	cd $(SOURCE_DIR)/GrxUIonEclipse-project-0.9.8 && java -Dorg.osgi.framework.os.version=`uname -r` -jar /usr/lib/eclipse/plugins/org.eclipse.equinox.launcher_*.jar -application org.eclipse.ant.core.antRunner -buildfile grxui_build.xml -verbose clean build.update.jar 2>&1 | tee build.log; if [ "`grep ERROR build.log`" ] ; then exit 1; fi
-	cp $(SOURCE_DIR)/GrxUIonEclipse-project-0.9.8/com.generalrobotix.ui.grxui_0.9.8.jar ${CURDIR}/eclipse/grxui/plugins
+	cp `rospack find openhrp3`/grxui_build_`uname -m`.xml $(SVN_DIR)/GrxUIonEclipse-project-0.9.8/grxui_build.xml
+	cp `rospack find openhrp3`/javaCompiler.grxui_`uname -m`.jar.args $(SVN_DIR)/GrxUIonEclipse-project-0.9.8/javaCompiler.grxui.jar.args
+	cd $(SVN_DIR)/GrxUIonEclipse-project-0.9.8 && java -Dorg.osgi.framework.os.version=`uname -r` -jar /usr/lib/eclipse/plugins/org.eclipse.equinox.launcher_*.jar -application org.eclipse.ant.core.antRunner -buildfile grxui_build.xml -verbose clean build.update.jar 2>&1 | tee build.log; if [ "`grep ERROR build.log`" ] ; then exit 1; fi
+	cp $(SVN_DIR)/GrxUIonEclipse-project-0.9.8/com.generalrobotix.ui.grxui_0.9.8.jar ${CURDIR}/eclipse/grxui/plugins
 	-rm -f ${CURDIR}/build/grxui_eclipse.zip
 	cd ${CURDIR}/eclipse/grxui; zip -urq  ${CURDIR}/build/grxui_eclipse.zip *  -x '*/.svn/*'
 
